# Uncomment the next line to define a global platform for your project
platform :ios, '11.3'

target 'MyLaugh' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyLaugh
  pod 'AFNetworking','~>3.1.0'
end
